<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Yatspec Index</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" type="text/javascript"></script>
    $stylesheet:{
    <style type="text/css">
            /* <![CDATA[ */
        $it$

            /* ]]> */
    </style>
    }$
    $script:{
    <script type="text/javascript">
        // <![CDATA[
        $it$
        // ]]>
    </script>
    }$
</head>
<body>

<h1>Index</h1>

<div class="contents">
    $result.packages:indexPackage(package=it, cssClass=cssClass)$
</div>
</body>
</html>
